### ISSUE TITLE
WindowInfoRepositoryCallbackAdapter is final and cannot be mocked in tests

### ISSUE THREAD

**Issue by andreidiaconu** [androidx/androidx#237]
I would like to propose that `WindowInfoRepositoryCallbackAdapter` be made `open` https://github.com/androidx/androidx/blob/632ddcdce0a1dca86b3830ae6e38a751fbd3d8e3/window/window-java/src/main/java/androidx/window/java/layout/WindowInfoRepositoryCallbackAdapter.kt#L37 in order to allow for it to be mocked during testing.

Some context:
Hi. We are using this adapter class in the Flutter support for foldables. That project uses Java, not kotlin, in both tests and tested code, so using the adapter makes sense to use. Unfortunately, the adapter class is final, which means I actually need to mock the underlying `WindowInfoRepository` and work with coroutines in tests instead. Since the tests are java, this makes testing very cumbersome - I'm not even sure I can use `Flow` / `Channel` / coroutines effectively. The adapter makes the internals of `WindowInfoRepository` transparent, which is great - but if I'm not able to mock it during testing, the internals become important.

I already tried configuring mockito for mocking final classes but there are other tests that don't seem to play nice with that configuration. I ended up wrapping the adapter in a delegate, which I control and can leave open for mocking - but I hope you agree this situation could be improved for java users of the `androidx.window` lib.

Thank you!

**Comment by dlam** [comment]
This issue tracker on Github isn't actively followed by Googlers. Please follow the links in the template to file a bug at issuetracker.google.com against the androidx.window component.
