### ISSUE TITLE
Why is a heading() semantic not defined for the AppBar title content?

### ISSUE THREAD

**Issue by dazza5000** [androidx/androidx#305]
This is in reference to the implementation below

https://github.com/androidx/androidx/blob/13b6d1df2e2c199d8fac54ae145c1d5ab7d30a87/compose/material/material/src/commonMain/kotlin/androidx/compose/material/AppBar.kt#L105-L115

**Comment by dlam** [comment]
Hi @dazza5000 , the issues on our Github aren't being actively triaged by androidx maintainers, so I'd recommend to file a bug on buganizer here: https://b.corp.google.com/issues/new?component=742043&template=1590761

**Comment by az-oolloow** [comment]
@dlam how do we raise the bugs on buganizer as members of the public? It requires a 'google corp' login

**Comment by dlam** [comment]
Sorry, I had linked an internal URL, but buganizer is public, fixed now !

For all of our supported libraries on Github we also have the corresponding buganizer new issue template URL for each library in the new issue template.
