### ISSUE TITLE
waitForWindowInsetsUntil vs composeRule.waitUntil

### ISSUE THREAD

**Issue by rlatapy-luna** [androidx/androidx#481]
https://github.com/androidx/androidx/blob/4fd035860243984314ed5404e4755cc135de3a1a/compose/foundation/foundation/src/androidAndroidTest/kotlin/androidx/compose/foundation/text/KeyboardHelper.kt#L147

- Why not use `composeRule.waitUntil` to wait the keyboard?
- I tried to use it in my test which uses `ActivityScenario.launch(MainActivity::class.java)`, but it seems that `waitForWindowInsetsUntil` block the UI? Using `composeRule.waitUntil` works for me.

**Comment by dlam** [comment]
Sorry for the late reponse here, but we don't monitor issues on GitHub, so if this is still important I would recommend to file a bug on our official [issue tracker](https://issuetracker.google.com/).
