### ISSUE TITLE
Could you add some sample for HeifWriter#addExifData?

### ISSUE THREAD

**Issue by GuaiYiHu** [androidx/androidx#517]
https://github.com/androidx/androidx/blob/a8933075bf9a92f1a1db0486848824fb1c2c5d8c/heifwriter/heifwriter/src/main/java/androidx/heifwriter/HeifWriter.java#L449

**Comment by dlam** [comment]
Sorry for the late reponse here, but we don't monitor issues on GitHub, so if this is still important I would recommend to file a bug on our official [issue tracker](https://issuetracker.google.com/).
