### ISSUE TITLE
splashcreen icon causes crash on API23 and below

### ISSUE THREAD

**Issue by bmx666** [androidx/androidx#575]
If set icon as vector drawable with gradient tag then app will crush on Android API23 and below because it does not support gradient tag.
Bug here ->
https://github.com/androidx/androidx/blob/274afc9dd9f3ac6ed75070bd3e371fdcc9863624/core/core-splashscreen/src/main/java/androidx/core/splashscreen/SplashScreen.kt#L264

Solution -> wrap into **AppCompatResources**
```kotlin
icon = AppCompatResources.getDrawable(activity, typedValue.resourceId)
```

**Comment by dlam** [comment]
Sorry for the late reponse here, but we don't monitor issues on GitHub, so if this is still important I would recommend to file a bug on our official [issue tracker](https://issuetracker.google.com/).
